--
-- PostgreSQL database dump
--

-- Dumped from database version 16.6
-- Dumped by pg_dump version 16.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: client_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.client_applications (
    client_id integer NOT NULL,
    app_id text,
    app_title text,
    version text,
    url text,
    api_url text,
    created_at timestamp without time zone,
    last_update timestamp without time zone,
    proctor_edu boolean DEFAULT false,
    proctorio boolean DEFAULT false,
    superset_apache boolean DEFAULT false,
    last_ping_successful boolean DEFAULT false,
    is_active boolean DEFAULT false
);


ALTER TABLE public.client_applications OWNER TO postgres;

--
-- Name: client_applications_client_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.client_applications ALTER COLUMN client_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.client_applications_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services (
    id text NOT NULL,
    app_id text NOT NULL,
    type character varying(50) NOT NULL,
    last_ping timestamp without time zone,
    status character varying(20)
);


ALTER TABLE public.services OWNER TO postgres;

--
-- Name: statistics_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.statistics_log (
    id text NOT NULL,
    recorded_at timestamp without time zone NOT NULL,
    user_cnt integer,
    active_users integer,
    locked_users integer,
    suspended_users integer,
    pending_users integer,
    inactive_users integer,
    user_group_cnt integer,
    root_user_group_cnt integer,
    avg_users_per_group numeric,
    admin_cnt integer,
    proctor_cnt integer,
    instructor_cnt integer,
    student_cnt integer,
    custom_role_cnt integer,
    all_pools integer,
    all_root_pools integer,
    all_pools_with_questions integer,
    avg_questions_in_pools numeric,
    single_choice_questions integer,
    multiple_choice_questions integer,
    essay_questions integer,
    true_false_questions integer,
    matrix_questions integer,
    matching_questions integer,
    fill_in_blanks_questions integer,
    ordering_questions integer,
    hotspot_questions integer,
    open_ended_questions integer,
    def_correctincorrect_scoring integer,
    by_answer_weight_scoring integer,
    manual_scoring integer,
    by_combination_scoring integer,
    by_rules_scoring integer,
    custom_question_properties integer,
    default_tests integer,
    only_tests_with_sections integer,
    all_manual_tests integer,
    all_generated_tests integer,
    generated_by_category_tests integer,
    avg_test_versions_root_tests numeric,
    max_test_versions_root_tests integer,
    avg_test_versions_root_sec numeric,
    max_test_versions_root_sec integer,
    test_templates integer,
    limited_time_tests integer,
    unlimited_time_tests integer,
    duration_per_question_tests integer,
    duration_per_quiz_tests integer,
    deadline_per_quiz_tests integer,
    test_one_page integer,
    test_page_per_question integer,
    after_test_report integer,
    after_grading_report integer,
    after_verification_report integer,
    on_manager_approval_report integer,
    realtime_grading integer,
    score_details integer,
    only_score integer,
    test_certificates integer,
    surveys integer,
    self_enrollment_global integer,
    session_user_groups integer,
    session_training integer,
    proctoredu integer,
    proctorio integer,
    favorite_reports integer,
    scheduled_reports integer,
    training_courses integer,
    pinned_courses integer,
    avg_steps_per_training numeric,
    avg_tests_per_training numeric,
    enabled_email_notifications integer,
    disabled_email_notifications integer,
    enabled_app_notifications integer,
    disabled_app_notifications integer,
    language_bundles integer,
    users_logged_all_time integer,
    users_logged_last_month integer,
    users_created_last_month integer,
    qpools_created_last_month integer,
    questions_in_qpools_last_month integer,
    attempts_last_month integer,
    total_attempts integer,
    test_attempts_last_month integer,
    total_test_attempts integer,
    survey_attempts_last_month integer,
    total_survey_attempts integer,
    max_concurrent_users_ever integer,
    max_concurrent_users_last_mont integer,
    failed_logins_last_month integer,
    failed_emails integer,
    unfinished_attempts integer,
    unfinished_disconnected_attemp integer,
    unfinished_in_progress_attemp integer,
    unfinished_avb_continue_attemp integer,
    unfinished_suspended_attemp integer,
    has_state_defined integer,
    has_country_defined integer,
    total_questions integer,
    accounting_questions integer,
    app_id text NOT NULL
);


ALTER TABLE public.statistics_log OWNER TO postgres;

--
-- Name: TABLE statistics_log; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.statistics_log IS 'Table which contains statistics information about app usage.';


--
-- Name: COLUMN statistics_log.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.id IS 'string identifier (UUID from GetCertified app)';


--
-- Name: COLUMN statistics_log.recorded_at; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.recorded_at IS 'recorded_at';


--
-- Name: COLUMN statistics_log.user_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.user_cnt IS 'Number of all users';


--
-- Name: COLUMN statistics_log.active_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.active_users IS 'Number of ACTIVE users';


--
-- Name: COLUMN statistics_log.locked_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.locked_users IS 'Number of LOCKED users';


--
-- Name: COLUMN statistics_log.suspended_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.suspended_users IS 'Number of SUSPENDED users';


--
-- Name: COLUMN statistics_log.pending_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.pending_users IS 'Number of PENDING users';


--
-- Name: COLUMN statistics_log.inactive_users; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.inactive_users IS 'Number of INACTIVE users';


--
-- Name: COLUMN statistics_log.user_group_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.user_group_cnt IS 'Number of all groups';


--
-- Name: COLUMN statistics_log.root_user_group_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.root_user_group_cnt IS 'Number of root user groups (parent_course_id is null)';


--
-- Name: COLUMN statistics_log.avg_users_per_group; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.avg_users_per_group IS 'Average number of users per group';


--
-- Name: COLUMN statistics_log.admin_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.admin_cnt IS 'Number of admins - users with role ADMIN';


--
-- Name: COLUMN statistics_log.proctor_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.proctor_cnt IS 'Number of proctors - users with role PROCTOR';


--
-- Name: COLUMN statistics_log.instructor_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.instructor_cnt IS 'Number of instructors - users with role INSTRUCTOR ';


--
-- Name: COLUMN statistics_log.student_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.student_cnt IS 'Number of students - users with role ATTENDEE ';


--
-- Name: COLUMN statistics_log.custom_role_cnt; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.custom_role_cnt IS 'Number of users with custom role type - role which is not in default roles (admin, attendee, instructor, proctor, )';


--
-- Name: COLUMN statistics_log.all_pools; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.all_pools IS 'Number of all pools of questions';


--
-- Name: COLUMN statistics_log.all_root_pools; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.all_root_pools IS 'Number of all root pools (parent_pool_id is null)';


--
-- Name: COLUMN statistics_log.all_pools_with_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.all_pools_with_questions IS 'Number of all pools with questions';


--
-- Name: COLUMN statistics_log.avg_questions_in_pools; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.avg_questions_in_pools IS 'Average number of questions in pools';


--
-- Name: COLUMN statistics_log.single_choice_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.single_choice_questions IS 'Number of single choice type of questions';


--
-- Name: COLUMN statistics_log.multiple_choice_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.multiple_choice_questions IS 'Number of multiple choice type of questions
';


--
-- Name: COLUMN statistics_log.essay_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.essay_questions IS 'Number of essay type of questions
';


--
-- Name: COLUMN statistics_log.true_false_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.true_false_questions IS 'Number of true/false type of questions';


--
-- Name: COLUMN statistics_log.matrix_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.matrix_questions IS 'Number of matrix type of questions
';


--
-- Name: COLUMN statistics_log.matching_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.matching_questions IS 'Number of matching type of questions';


--
-- Name: COLUMN statistics_log.fill_in_blanks_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.fill_in_blanks_questions IS 'Number of fill in the blanks type of questions';


--
-- Name: COLUMN statistics_log.ordering_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.ordering_questions IS 'Number of ordering type of questions';


--
-- Name: COLUMN statistics_log.hotspot_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.hotspot_questions IS 'Number of hotspot type of questions
';


--
-- Name: COLUMN statistics_log.open_ended_questions; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.open_ended_questions IS 'Number of open-ended type of questions';


--
-- Name: COLUMN statistics_log.def_correctincorrect_scoring; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.def_correctincorrect_scoring IS 'Number of questions with scoring type by defining correct/incorrect answers ';


--
-- Name: COLUMN statistics_log.by_answer_weight_scoring; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.by_answer_weight_scoring IS 'Number of questions with scoring type by answer weight ';


--
-- Name: COLUMN statistics_log.manual_scoring; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.manual_scoring IS 'Number of questions with manual scoring type';


--
-- Name: COLUMN statistics_log.by_combination_scoring; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.by_combination_scoring IS 'Number of questions with scoring type by combination scoring';


--
-- Name: COLUMN statistics_log.by_rules_scoring; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.by_rules_scoring IS 'Number of questions with scoring type by rules';


--
-- Name: COLUMN statistics_log.custom_question_properties; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.custom_question_properties IS 'Number of questions with custom properties';


--
-- Name: COLUMN statistics_log.default_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.default_tests IS 'Number of default tests (prev_quiz_def_id is null)';


--
-- Name: COLUMN statistics_log.only_tests_with_sections; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.only_tests_with_sections IS 'Number of tests with sections';


--
-- Name: COLUMN statistics_log.all_manual_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.all_manual_tests IS 'Number of all tests manually created';


--
-- Name: COLUMN statistics_log.all_generated_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.all_generated_tests IS 'Number of all generated tests';


--
-- Name: COLUMN statistics_log.generated_by_category_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.generated_by_category_tests IS 'generated_by_category_tests';


--
-- Name: COLUMN statistics_log.avg_test_versions_root_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.avg_test_versions_root_tests IS 'Average number of test versions per root tests';


--
-- Name: COLUMN statistics_log.max_test_versions_root_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.max_test_versions_root_tests IS 'Max number of test versions per root tests';


--
-- Name: COLUMN statistics_log.avg_test_versions_root_sec; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.avg_test_versions_root_sec IS 'Average number of test versions per root section';


--
-- Name: COLUMN statistics_log.max_test_versions_root_sec; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.max_test_versions_root_sec IS 'Max number of test versions per root section';


--
-- Name: COLUMN statistics_log.test_templates; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.test_templates IS 'Number of test templates';


--
-- Name: COLUMN statistics_log.limited_time_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.limited_time_tests IS 'Number of tests with limited time';


--
-- Name: COLUMN statistics_log.unlimited_time_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.unlimited_time_tests IS 'Number of tests with unlimited time ';


--
-- Name: COLUMN statistics_log.duration_per_question_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.duration_per_question_tests IS 'Number of tests with duration type per question';


--
-- Name: COLUMN statistics_log.duration_per_quiz_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.duration_per_quiz_tests IS 'Number of tests with duration type per quiz where timer does not tick when attempt is paused';


--
-- Name: COLUMN statistics_log.deadline_per_quiz_tests; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.deadline_per_quiz_tests IS 'Number of tests with deadline per quiz duration type where timer ticks when attempt is paused';


--
-- Name: COLUMN statistics_log.test_one_page; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.test_one_page IS 'Number of tests with look type where all questions are on one page';


--
-- Name: COLUMN statistics_log.test_page_per_question; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.test_page_per_question IS 'Number of tests with look type in which there is one question per page';


--
-- Name: COLUMN statistics_log.after_test_report; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.after_test_report IS 'Number of tests with reporting Immediatly after finish (IAF)';


--
-- Name: COLUMN statistics_log.after_grading_report; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.after_grading_report IS 'Number of tests with reporting immediatly after finishing whole quiz (IMM)';


--
-- Name: COLUMN statistics_log.after_verification_report; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.after_verification_report IS 'Number of tests with reporting immediatly after verification (IAV)';


--
-- Name: COLUMN statistics_log.on_manager_approval_report; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.on_manager_approval_report IS 'Number of tests with reporting on manager (professor) approval (OPA)';


--
-- Name: COLUMN statistics_log.realtime_grading; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.realtime_grading IS 'Number of tests with reporting after every question (IQT), for wizard type of quiz. ';


--
-- Name: COLUMN statistics_log.score_details; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.score_details IS 'Number of tests with results full display (grade and preview)';


--
-- Name: COLUMN statistics_log.only_score; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.only_score IS 'Number of tests with only grade displayed as a result';


--
-- Name: COLUMN statistics_log.test_certificates; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.test_certificates IS 'Number of test certificates';


--
-- Name: COLUMN statistics_log.surveys; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.surveys IS 'Number of surveys';


--
-- Name: COLUMN statistics_log.self_enrollment_global; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.self_enrollment_global IS 'Number of testing sessions where selfenrollment is enabled';


--
-- Name: COLUMN statistics_log.session_user_groups; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.session_user_groups IS 'Number of user group sessions';


--
-- Name: COLUMN statistics_log.session_training; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.session_training IS 'Number of training sessions';


--
-- Name: COLUMN statistics_log.proctoredu; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.proctoredu IS 'Number of testing sessions with proctoredu integration';


--
-- Name: COLUMN statistics_log.proctorio; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.proctorio IS 'Number of testing sessions with proctorio integration';


--
-- Name: COLUMN statistics_log.favorite_reports; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.favorite_reports IS 'Number of favorite reports';


--
-- Name: COLUMN statistics_log.scheduled_reports; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.scheduled_reports IS 'Number of scheduled reports';


--
-- Name: COLUMN statistics_log.training_courses; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.training_courses IS 'Number of training courses';


--
-- Name: COLUMN statistics_log.pinned_courses; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.pinned_courses IS 'Number of lessons where user can self-enroll';


--
-- Name: COLUMN statistics_log.avg_steps_per_training; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.avg_steps_per_training IS 'Average number of steps per training';


--
-- Name: COLUMN statistics_log.avg_tests_per_training; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.avg_tests_per_training IS 'Average number of tests per training';


--
-- Name: COLUMN statistics_log.enabled_email_notifications; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.enabled_email_notifications IS 'Number of enabled email notifications';


--
-- Name: COLUMN statistics_log.disabled_email_notifications; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.disabled_email_notifications IS 'Number of disabled email notifications';


--
-- Name: COLUMN statistics_log.enabled_app_notifications; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.enabled_app_notifications IS 'Number of enabled application notifications';


--
-- Name: COLUMN statistics_log.disabled_app_notifications; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.disabled_app_notifications IS 'Number of disabled application notifications
';


--
-- Name: COLUMN statistics_log.language_bundles; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.language_bundles IS 'Number of active (displayed) language bundles';


--
-- Name: COLUMN statistics_log.users_logged_all_time; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.users_logged_all_time IS 'Number of distinct non-admin users who have ever logged in (since the logging started)';


--
-- Name: COLUMN statistics_log.users_logged_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.users_logged_last_month IS 'Number of users logged in last month';


--
-- Name: COLUMN statistics_log.users_created_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.users_created_last_month IS 'Number of users created last month';


--
-- Name: COLUMN statistics_log.qpools_created_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.qpools_created_last_month IS 'Number of question pools created last month';


--
-- Name: COLUMN statistics_log.questions_in_qpools_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.questions_in_qpools_last_month IS 'Number of question created in pools last month';


--
-- Name: COLUMN statistics_log.attempts_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.attempts_last_month IS 'Number of all attempts last month';


--
-- Name: COLUMN statistics_log.total_attempts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.total_attempts IS 'Number of all attempts since ever';


--
-- Name: COLUMN statistics_log.test_attempts_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.test_attempts_last_month IS 'Number of test attempts last month';


--
-- Name: COLUMN statistics_log.total_test_attempts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.total_test_attempts IS 'Number of all test attempts since ever';


--
-- Name: COLUMN statistics_log.survey_attempts_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.survey_attempts_last_month IS 'Number of all survey attempts last month';


--
-- Name: COLUMN statistics_log.total_survey_attempts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.total_survey_attempts IS 'Number of all survey attempts since ever';


--
-- Name: COLUMN statistics_log.max_concurrent_users_ever; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.max_concurrent_users_ever IS 'Maximal number of concurrent users since ever';


--
-- Name: COLUMN statistics_log.max_concurrent_users_last_mont; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.max_concurrent_users_last_mont IS 'Maximal number of concurrent users last month';


--
-- Name: COLUMN statistics_log.failed_logins_last_month; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.failed_logins_last_month IS 'Number of failed logins last month';


--
-- Name: COLUMN statistics_log.failed_emails; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.failed_emails IS 'Number of failed emails (which are failed to be sent)';


--
-- Name: COLUMN statistics_log.unfinished_attempts; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.unfinished_attempts IS 'Number of unfinished attempts';


--
-- Name: COLUMN statistics_log.unfinished_disconnected_attemp; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.unfinished_disconnected_attemp IS 'Number of unfinished disconnected attempts';


--
-- Name: COLUMN statistics_log.unfinished_in_progress_attemp; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.unfinished_in_progress_attemp IS 'Number of unfinished in progress attempts';


--
-- Name: COLUMN statistics_log.unfinished_avb_continue_attemp; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.unfinished_avb_continue_attemp IS 'Number of unfinished attempts available to be continued';


--
-- Name: COLUMN statistics_log.unfinished_suspended_attemp; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.unfinished_suspended_attemp IS 'Number of unfinished suspended attempts';


--
-- Name: COLUMN statistics_log.has_state_defined; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.has_state_defined IS 'Number of users who has state of living defined';


--
-- Name: COLUMN statistics_log.has_country_defined; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.statistics_log.has_country_defined IS 'Number of users who has country defined';


--
-- Name: client_applications client_applications_app_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client_applications
    ADD CONSTRAINT client_applications_app_id_key UNIQUE (app_id);


--
-- Name: client_applications client_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.client_applications
    ADD CONSTRAINT client_applications_pkey PRIMARY KEY (client_id);


--
-- Name: statistics_log pk_statistics_log; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statistics_log
    ADD CONSTRAINT pk_statistics_log PRIMARY KEY (id);


--
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- Name: services fk_client_app_services_app_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT fk_client_app_services_app_id FOREIGN KEY (app_id) REFERENCES public.client_applications(app_id) ON DELETE CASCADE;


--
-- Name: statistics_log fk_statistics_log_app_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statistics_log
    ADD CONSTRAINT fk_statistics_log_app_id FOREIGN KEY (app_id) REFERENCES public.client_applications(app_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

